# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# CREDITS
# This has been adopted from https://github.com/deshraj/deshraj.github.io/

# SITE SETTINGS
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piyush Bagad
email: piyushnbagad11@gmail.com
repository: bpiyush/bpiyush.github.io
description: >- # this means to ignore newlines until "baseurl:"
  Piyush Bagad is currently a Research Fellow at Wadhwani AI. He graduated with B.S. in Math from IIT Kanpur in 2019.
  He works in the space of AI for Social Good: To leverage AI to help the next 5 billion people.
  He is interested in 3D Computer vision (particularly related to human motion), learning from audio-video. On the side, he also loves Bayesian inference.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bpiyush.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bagad_piyush
github_username:  bpiyush

# BUILD SETTINGS
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
